# Site settings
title: CS12 SI @ UCR
email: jbeto001@ucr.edu
description: >
  This website will be used for CS012 SI for Fall 2018
lang: en-US

baseurl: "/CS12_Fall_2018" # the subpath of your site, e.g. /blog/
url: https://cs-si-ucr.github.io/CS12_Fall_2018/ # the base hostname & protocol for your site
git_address: https://github.com/cs-si-ucr/CS12_Fall_2018
git_edit_address: https://github.com/cs-si-ucr/CS12_Fall_2018

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
bootwatch: cosmo

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
timezone: Europe/Berlin
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true
